(function () {
  angular.module('NarrowItDownApp',[])
  .controller('NarrowItDownController', NarrowItDownController)
  .service('MenuSearchService', MenuSearchService)
  .constant('MenuPath', "https://davids-restaurant.herokuapp.com/menu_items.json")
  .directive('foundItems', FoundItemsDirective);

  function FoundItemsDirective() {
    var ddo = {
    templateUrl: 'narrowedList.html',
    scope: {
      found: '<',
      removeItem: '&removeItemAt'
    },
    link: FoundItemsLink,
    controller: FoundItemsController,
    bindToController: true,
    controllerAs: 'foundControl',
    };

    return ddo;
  }

  function FoundItemsLink(scope, element, attrs, controller) {
    var warningElem = element.find("div.error");
    var itemsTable = element.find("table.table");

    scope.$watch('foundControl.found',function (newValue, oldValue) {
      if (newValue!= undefined) {
        if (newValue.length === 0) {
          itemsTable.css('display', 'none');
          warningElem.slideDown(900);
        }else {
          warningElem.css('display', 'none');
          itemsTable.css('display', 'block');
        }
      }
    });
  }

  function FoundItemsController() {
    var found = this;
  }

  NarrowItDownController.$inject = ['MenuSearchService'];
  function NarrowItDownController(MenuSearchService) {
    var narrow = this;
    narrow.searchTerm = "";
    narrow.getMatchedItems = function (searchTerm) {
      if (narrow.searchTerm) {
        var searchedItemsPromise = MenuSearchService.getMatchedMenuItems(searchTerm);
        searchedItemsPromise.then(function (response) {
          narrow.found = response;
        });
      }else {
        narrow.found = [];
      }
    };
    narrow.removeItemAt = function (index) {
      narrow.found.splice(index,1);
    };
  }

  MenuSearchService.$inject = ['$http', 'MenuPath'];
  function MenuSearchService($http, MenuPath) {
    var search = this;
    search.getMatchedMenuItems = function (searchTerm) {
      //retrieve the list of menu items
      var promise = $http({
        method: "GET",
        url: (MenuPath)
      });

      //Returns the promise generated by "$http.then()" method
      return promise.then(function (response) {
        //Gets the JSON elements returned by the HTTP request.
        var objectList = response.data.menu_items;
        var foundItems = [];
        //Loops through the menu items
        for (var i = 0; i < objectList.length; i++) {
          //Checks whether the element's description contains the searched parameter
          if (objectList[i].description.indexOf(searchTerm) !== -1) {
            foundItems.push(objectList[i]);
          }
        }
        return foundItems;
      });
    };
  }

})();
